-- SQLite-compatible schema generated by SQLAlchemy model.
CREATE TABLE inspection_records (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    inspection_id VARCHAR(64) NOT NULL UNIQUE,
    frame_id INTEGER NOT NULL,
    inspected_at DATETIME NOT NULL,
    passed BOOLEAN NOT NULL,
    confidence FLOAT NOT NULL,
    measurements_json TEXT NOT NULL,
    failure_reasons_json TEXT NOT NULL,
    roi_json TEXT NOT NULL DEFAULT '',
    image_path VARCHAR(512) NOT NULL DEFAULT '',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_inspection_records_inspected_at ON inspection_records (inspected_at);
CREATE INDEX idx_inspection_records_frame_id ON inspection_records (frame_id);
CREATE INDEX idx_inspection_records_passed ON inspection_records (passed);

